### PR TITLE
Adds service, a little bit of maint

### PR DESCRIPTION
**Pull request by fortnitegamer2016**
As a wise man once said `"no station can exist without the dicksuckatorium."` and they were right, so to sum it up it makes the station exist.

****How I gained ED after 6 hours at Freddy Fuckbears Pimphouse****
i the belive this adintion to station woul be beneficialy för multidle rsons 
1. u are trap (::::::::::::::::::
2. sussy baka

If this doesnt get merged I will shit in your bed without wiping.

### CODE REVIEW

**Comment by HahafunnymanXD** [comment]
no wiser words than this could possibly exist

**Comment by fortnitegamer2016** [comment]
****black people****

**Comment by HahafunnymanXD** [comment]
ew

**Comment by djpotatopug1432** [comment]
doesnt work lmao

**Comment by fortnitegamer2016** [comment]
check your bed

**Pull request closed without merging**
